arytest/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('', 
    url(r'^admin/', include(admin.site.urls)),
    #Sessions
    url(r'^accounts/', include('allauth.urls')),
    #il8n
    (r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('common.urls')),                  
)

common/urls.py
## -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from common import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
	#url(r'^$', 'common.views.logueo'),
	#url(r'^inicio/$', 'common.views.logueo'),
	url(r'^$', 'common.views.addTarea', name='add_tarea'),
	url(r'^otro/$', 'common.views.addUsuario', name='add_ususario'),
	url(r'^edit/tarea/(?P<pk>[0-9]+)/$', 'common.views.editTarea', name='edit_tarea'),
	url(r'^delete/tarea/(?P<pk>[0-9]+)/$', 'common.views.deleteTarea', name='delete_tarea'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

common/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
from django.db.models import Count
from django.db.models.signals import post_save

from allauth.account.adapter import DefaultAccountAdapter
from allauth.account.models import EmailAddress

## Create your models here.

class Tarea(models.Model):
    user = models.ForeignKey(User)
    nombre = models.CharField("Nombre de la Tarea",max_length=50)
    descripcion = models.TextField("Detalles de la Tarea")
    realizada = models.BooleanField("Realizada", help_text="¿Se encuentra realizada?", default=False)
    fecha_registro_tarea = models.DateTimeField("Fecha en que se registra la tarea", help_text="Formato dia/mes/año Hora:Minutos", null=True, blank=True )
    fecha_realizada_tarea = models.DateTimeField("Fecha en que fue realizada la tarea", help_text="Formato dia/mes/año Hora:Minutos", null=True, blank=True)
    
    def __unicode__(self):
        return  self.nombre + '-' + self.realizada + '-' + self.fecha_registro_tarea+ '-' + self.fecha_realizada_tarea
    
    class Meta:
        verbose_name = "Tarea"
        verbose_name_plural = "Tareas"    


class Perfil(models.Model):
    user = models.OneToOneField(User)
    privado = models.BooleanField("Privado", help_text="¿Perfil Privado?", default=False)
    
    class Meta:
        app_label = "auth"
        verbose_name = "Perfil"
        verbose_name_plural = "Perfiles"

def create_user_profile(sender, instance, created, **kwargs):  
    if created:
       Perfil.objects.create(user=instance)
       if not EmailAddress.objects.filter(email=instance.email):
           address = EmailAddress(user=instance, email=instance.email, verified=True, primary=True)

post_save.connect(create_user_profile, sender=User)

common/forms.py
## -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from django.template.loader import render_to_string
from django.shortcuts import render_to_response
from django.forms.util import ErrorList
import datetime
from .models import Tarea, Perfil

##------Custom widget para los select------#
class SelectWithPop(forms.Select):
    def render(self, name, *args, **kwargs):
        html = super(SelectWithPop, self).render(name, *args, **kwargs)
        popupplus = render_to_string("form/popupplus.html", {'field': name})
        return html+popupplus
##-----------------------------------------#

##------Custom widget para los select múltiples------#
class SelectWithPopMultiple(forms.SelectMultiple):
    def render(self, name, *args, **kwargs):
        html = super(SelectWithPopMultiple, self).render(name, *args, **kwargs)
        popupplus = render_to_string("form/popupplus.html", {'field': name})
        return html+popupplus
##-----------------------------------------#

class TareasForm(ModelForm):
    class Meta:
        model = Tarea
        exclude = ['user']
    
Lista_Tareas = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Tarea.objects.all(), required=False)

class PerfilForm(ModelForm):
    class Meta:
        model=Perfil
    
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@gmail.com" not in data:
            raise forms.ValidationError("Invalid email!")

        # Always return the cleaned data, whether you have changed it or
        # not.
        return data


class TareaFormEdit(ModelForm):
	class Meta:
		model = Tarea

common/views.py
#encoding:utf-8
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.template import RequestContext
from django.template.loader import render_to_string
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.core.validators import validate_email
from django.db.models import Count, Avg, Sum
from django.utils.html import escape
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.http import HttpResponse
import datetime
from django.utils.timezone import utc
from django.db.models import Count, Avg, Sum
from django import forms
from .forms import TareasForm, PerfilForm
from .models import Tarea, Perfil

# Create your views here.
	    
def addUsuario(request):
	if request.method == 'POST':
		perfil_form = PerfilForm(request.POST)
		
		if perfil_form.is_valid():
			perfil_form.save()
			return render_to_response('common/otro.html', {'mensaje': 'Formulario guardado correctamente'}, context_instance=RequestContext(request))
		else:
			return render_to_response('common/otro.html', locals(), context_instance=RequestContext(request))
	else:
		perfil_form = PerfilForm()

		
	return render_to_response('common/otro.html', locals(), context_instance=RequestContext(request))

@login_required
def addTarea(request):
	form = TareasForm()
	if request.method == 'POST':
		form = TareasForm(request.POST)
        if form.is_valid():
		    tarea = form.save(commit=False)
		    tarea.user = request.user
		    tarea.save()
		    return HttpResponseRedirect('/')					
	return render_to_response('common/add_tarea.html',{'form' : form}, context_instance=RequestContext(request))

@login_required
def editTarea(request, pk):
    tarea = get_object_or_404(Tarea, pk=pk)
    mensaje = None
    formTarea = TareasForm(instance=tarea)
    if request.method == 'POST':
		if tarea.realizada == False:
			formTarea = TareasForm(request.POST, instance=tarea)
			if formTarea.is_valid():
				formTarea.save()				
				mensaje = "Tarea modificada con éxito"				
				
		else:
			mensaje = "No se puede editar una tarea marcada como realizada"
			print mensaje
		
    return render_to_response('common/edit_tarea.html', {'formTarea': formTarea, 'id': id, 'mensaje': mensaje }, context_instance=RequestContext(request))

@login_required
def deleteTarea(request, pk):
	mensaje = ""
	fecha_actual = datetime.datetime.utcnow().replace(tzinfo=utc)
	td = get_object_or_404(Tarea, pk=pk)
	if (td.fecha_registro_tarea < fecha_actual):
		td.delete()
		mensaje = "La tarea ha sido eliminada con exito"
	else:
		mensaje = "La tarea no es considerada como antigua, no puede ser eliminada"
	
	return render_to_response("common/delete_tarea.html", {'mensaje': mensaje}, context_instance=RequestContext(request))

common/templates/common/add_tarea.html
{% extends 'common/base.html' %}

{% load bootstrap3 %}

{% block content %}

<div class="wrapper row2">
  <div id="container" class="container-fluid">
    <div class="row">
	  <div class="col-md-6">
        <form action="" method="post" role="form" >
		  {% csrf_token %}
		  <center><legend>Insertar Nueva Tarea</legend></center>
		  {% bootstrap_form form %}	
		  <button type="submit" class="btn btn-primary">Aceptar</button>
	      <button type="reset" class="btn btn-default">Cancelar</button>
		</form>
	  </div>

<div class="col-md-6">
 <center><legend>Mis Tareas:</legend></center>
<div class="table-responsive">
  <table class="table table-hover">
     <thead>
        <tr>
           <th>Tarea</th>
           <th>Estado</th>
           <th>Editar Tarea</th>
           <th>Eliminar Tarea</th>
        </tr>
     </thead>
     <tbody>
		{% for tarea in user.tarea_set.all %}
          <tr>
             <td>{{ tarea.nombre }}</td>
             <td><span class="badge">{{ tarea.realizada|yesno:"realizada,pendiente" }}</td>
             <td><a href="{% url 'edit_tarea' pk=tarea.pk %}"> Editar Tarea </a></td>
             <td><a href="{% url 'delete_tarea' pk=tarea.pk %}"> Eliminar Tarea </a></td>
           </tr>
        {% endfor %}
     </tbody>
   </table>
</div>
</div>


	</div>
  </div>
</div>
{% endblock %}




	
      
     

common/templates/common/base.html
{% load staticfiles %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Test Nexa</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "web/plugins/sbadmin2/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static "web/plugins/sbadmin2/vendor/metisMenu/metisMenu.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "web/plugins/sbadmin2/dist/css/sb-admin-2.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "web/plugins/sbadmin2/vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
{% if user.is_authenticated %}
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">


{% include "common/header.html" %}
{% include "common/menu-izq.html" %}            

          
         </nav>  
{% endif %} 
        <!-- Page Content -->
        
       
        
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
					
		{% block content %}
		Contenido de pagina
		{% endblock content %}

		
					
					
					
                    
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static "web/plugins/sbadmin2/vendor/jquery/jquery.min.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "web/plugins/sbadmin2/vendor/bootstrap/js/bootstrap.min.js" %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static "web/plugins/sbadmin2/vendor/metisMenu/metisMenu.min.js" %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static "web/plugins/sbadmin2/dist/js/sb-admin-2.js" %}"></script>

</body>

</html>

common/templates/common/delete_tarea.html
{% extends 'common/base.html' %}

{% load bootstrap3 %}

{% block content %}
<div class="row">
	{% if mensaje %}
	<div class="col-md-12">
		{% if mensaje %}<div class = "alert alert-info">{{mensaje}} &nbsp;<a href="/"> Volver </a> </div><br>
		
		
		{% endif %}
	</div>
	{% endif %}			
{% endblock %}

common/templates/common/edit_tarea.html
{% extends 'common/base.html' %}

{% load bootstrap3 %}

{% block content %}
<div class="row">
	{% if mensaje %}
	<div class="col-md-12">
		{% if mensaje %}<div class = "alert alert-warning">{{mensaje}} &nbsp;<a href="/"> Volver </a> </div><br>
		
		
		{% endif %}
	</div>
	{% endif %}			
	<div class="col-md-12">
		<h3>Editar tarea</h3>
		<hr>
		<form action="." method="post">
			{% csrf_token %}
			{% bootstrap_form formTarea %}
			<button type="submit" class="btn btn-primary">Aceptar</button>
		</form>
	</div>
</div>
{% endblock %}

common/templates/common/footer.html
<footer>

<p>footer</p>

</footer>

common/templates/common/header.html
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Test Nexa</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                   {% if user.is_authenticated %}
                   <p> Bienvenido {{user}}</p>
                   
                   {% endif %}
                   
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        
                        <li class="divider"></li>
                        <li><a href="{% url 'account_logout' %}"><i class="fa fa-sign-out fa-fw"></i> Salir</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>

common/templates/common/index.html
{% extends "common/base.html" %}

{% block contenido %}
        
<h1>Pagina Index</h1>
        
{% endblock contenido %}

common/templates/common/inicio.html
{% extends "common/base.html" %}

{% block contenido %}
        
<h1>Pagina Inicial</h1>
        
{% endblock contenido %}

common/templates/common/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Test Nexa</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "web/plugins/sbadmin2/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static "web/plugins/sbadmin2/vendor/metisMenu/metisMenu.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "web/plugins/sbadmin2/dist/css/sb-admin-2.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "web/plugins/sbadmin2/vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
{% block contenido %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">P&aacute;gina de Logueo</h3>
                    </div>
                    <div class="panel-body">
						{% if message %}
						<p>{{ message }}</p>
						{% endif %}
                        <form action="" method = " post " role="form">
							{% csrf_token %}
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Usuario" name="username" type="text" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Contraseña" name="password" type="password" value="">
                                </div>
                                
                                <!-- Change this to a button or input when using this as a form -->
                                  <input type="submit"  class="btn btn-outline btn-success btn-lg" value='Entrar'/>
                                  <br><br>
                                  <p class="text-primary"> No tienes una cuenta a&uacute;n?</p>
                                  
                               <input type='submit'  class="btn btn-outline btn-primary btn-lg" value='Autenticar'/>
                                
                                  
                                  
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery -->
    <script src="{% static "web/plugins/sbadmin2/vendor/jquery/jquery.min.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "web/plugins/sbadmin2/vendor/bootstrap/js/bootstrap.min.js" %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static "web/plugins/sbadmin2/vendor/metisMenu/metisMenu.min.js" %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static "web/plugins/sbadmin2/dist/js/sb-admin-2.js" %}"></script>

</body>

</html>






















{% endblock contenido %}

common/templates/common/menu-izq.html
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="#"><i class="fa fa-tasks fa-fw"></i> Tareas <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{% url 'add_tarea' %}">Agregar Tarea</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->

common/templates/common/otro.html
{% extends "common/base.html" %}
<!DOCTYPE html>
<html>
<head>
<title>Test Nexa</title>

</head>

{% block contenido %}
{% if mensaje %}
<div class="alert alert-info">{{ mensaje }}</div>
{% else %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">P&aacute;gina de Registro de Usuario</h3>
                    </div>
                    <div class="panel-body">
					<form action ="/" method="post" role="form">
					{% csrf_token %}
					<fieldset>
                     <div class="form-group">
					{% for error in perfil_form.errors %}
<tr style="background-color: red;"><th colspan="2">{{ error|capfirst }} incorrecto.</th></tr>
{% endfor %}

					
					<label>Usuario:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>{{ perfil_form.username }}
					<br>
					<label>Email(gmail):</label>{{ perfil_form.email }}
					<br>
					<label>Contraseña:&nbsp;</label>{{ perfil_form.password }}
					<br>
					<label>Privado:</label>&nbsp;{{ perfil_form.privado }}

					<br>
					{{ perfil_form.last_login.as_hidden}}
					{{ perfil_form.date_joined.as_hidden}}
					<input type="submit" value="enviar" name="enviar"/>
					</table>
					</form>

</div>
</div>
</div>
</div>
</div>
</div>




{% endif %}

{% endblock contenido %}

</html>